BOOTMAGIC_ENABLE  = yes
COMMAND_ENABLE    = yes
CONSOLE_ENABLE    = yes
EXTRAKEY_ENABLE   = yes
NKRO_ENABLE       = yes

AUDIO_ENABLE      = no
BACKLIGHT_ENABLE  = no
BLUETOOTH_ENABLE  = no
MIDI_ENABLE       = no
MOUSEKEY_ENABLE   = no
RGBLIGHT_ENABLE   = no
SLEEP_LED_ENABLE  = no
TAP_DANCE_ENABLE  = no
UNICODEMAP_ENABLE = no
